### ISSUE TITLE
Написать сервер на node.js для раздачи статики

### ISSUE THREAD

**Issue by rowbotman** [frontend-park-mail-ru/2020_1_Failless#13]
Нужен сервер на Node, чтобы можно было запускать проект без Nginx командой типа `npm run server`

**Comment by almashell** [comment]
Текущая версия сырая.
Требуются доработки согласно: https://app.swaggerhub.com/apis/rowbotman/Eventum/1.0.2

Може быть проблемой загрузка картинок.
