### ISSUE TITLE
Интегрировать валидацию (+починить addEventListener для корректных переходов между страницами)

### ISSUE THREAD

**Issue by rowbotman** [frontend-park-mail-ru/2020_1_Failless#15]
" не работает регистрация. приходят непонятные ошибки с бекенда
 вывод серверных ошибок на клиенте. тексты ошибок должны храниться на клиенте"  
Сверстать блоки ошибок, интегровать с валидационными скриптами, чтобы пользователь понимал, что происходит

**Comment by almashell** [comment]
Готова предварительная версия. Оттестирована на регистрации.

Требуется:
  - Нарисовать блоки-алармы для пользователя
  - Изменить структуру результата валидации (не массив массивов с ошибками, которые могут быть пустыми)
  - Добавить на авторизацию

**Comment by almashell** [comment]
Поломано окружение перехода по страницам.

Основной проблемный кандидат: 
```javascript 
document.addEventListener('DOMContentLoaded', () => {...}
```

Файлы для починки:
  - `public/js/core/controller.js`
  - `public/js/controllers/login-controller.js`
  - `public/js/controllers/signup-controller.js`

В т.ч.:
```javascript 
export default class Controller {

    /**
     * Construct obj of basic controller class
     * @param {HTMLElement} parent
     */
    constructor(parent) {
        this.parent = parent;
        document.addEventListener('DOMContentLoaded', () => {
            // TODO: add eventlisteners
        });
    }
...
}
```

**Comment by almashell** [comment]
Починить отдачу статики `/img/*`.

**Comment by almashell** [comment]
Реализую деструктор event listeners.
