### ISSUE TITLE
Профиль [2]

### ISSUE THREAD

**Issue by rowbotman** [frontend-park-mail-ru/2020_1_Failless#36]
Нужно релизовать обработчики на события - нажатие кнопки `добавить`:
- [ ]  `соц. сеть` (пока просто ссылку)  
- [x]  `тег`  
- [x]  `событие`

**Comment by egogoger** [comment]
Беру нажатие на "Добавить тег"

**Comment by egogoger** [comment]
"Добавить тег" [готово](https://github.com/frontend-park-mail-ru/2020_1_Failless/pull/45).
